SPHINX_PROJECT_NAME=SDRAM Component
VERSION=2.0
DOXYGEN_DIRS=../../sc_sdram_burst/module_sdram ../../sc_sdram_burst/module_sdram_memory_mapper
SOURCE_INCLUDE_DIRS=../../sc_sdram_burst
include $(XDOC_DIR)/Makefile.inc
