TARGET = XK-1
APP_NAME =
USED_MODULES = module_flash_small
XCC_FLAGS_Debug =
XCC_FLAGS_Release = -g -O2
VERBOSE = 0

XMOS_MAKE_PATH ?= ../..
-include $(XMOS_MAKE_PATH)/xcommon/module_xcommon/build/Makefile.common
